// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucmayetovibomctddmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y21heWV0b3ZpYm9tY3RkZG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTYwMzYsImV4cCI6MjA2MjM3MjAzNn0.qiIRvC3xAwHjwz-24vuKINdyUlFv29JTEZYBRwJQKEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);